### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fabianmossberg** [Lleweraf/supachat#3]
If you set an open source license, people could contribute.

I have some ideas for improvement, and would love to contribute.

**Comment by Lleweraf** [comment]
Hi! I have set up the license. Thank you very much

**Comment by Lleweraf** [comment]
> If you set an open source license, people could contribute.
> 
> I have some ideas for improvement, and would love to contribute.

Hi! I have set up the license. Thank you very much

**Comment by Lleweraf** [comment]
@fabianmossberg Hi! I have set up the license. Thank you very much
